# yaml-language-server: $schema=../node_modules/somod/node_modules/@somod/schema/ui-config/schemas/index.json

env: {}
imageDomains: []
publicRuntimeConfig:
  defaultThemeOptions:
    SOMOD::Parameter: ui.theme.options

serverRuntimeConfig: {}
